[package]
name = "jun"
version = "0.1.0"
edition = "2024"

[dependencies]
Inflector = "0.11.4"
clap = { version = "4.5.41", features = ["derive"] }
convert_case = "0.8.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tera = "1.20.0"
